title: "The Child Language Lab"
author: ""
description: "At the University of Pennsylvania"

# Jekyll settings
#permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 5                 # number of articles per page, remove to disable pagination
paginate_path: "/blog/page:num/"
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
excerpt_separator: <!--more--> # place this in posts where you want it to cut off
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
dark_theme: false            # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: true        # radically minimalistic theme


navigation:                  # show navigation links in the header
  - about.md
  - team.md
  - publications.md
  - for-participants.md
  - news.md
  - index.html
#  - archive.md

icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  github: "https://github.com/kschuler"
  twitter: "twitter.com"
  flask: "http://kschuler.github.io/childlanglabwiki"
#  feed: ""

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
